name: CI
on: [push]
jobs:
  build:
    strategy:
      matrix:
        java: [11]
        #os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Run command
      run: echo single line command..
    - name: Run Multi line commands
      run: |
        echo multi line command...
    - uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: 6.1.1
        arguments: clean build -S
    # https://github.com/actions/cache/blob/master/examples.md#java---gradle
    - name: Cache npm
      uses: actions/cache@v1
      with:
        path: ~/.npm
        #key: ${{ matrix.java }}-${{ matrix.os }}-cache
        key: java-${{ matrix.java }}-${{ runner.os }}-${{ matrix.os }}-gradle-${{ hashFiles('**/.npm/**') }}
        restore-keys: |
          java-${{ matrix.java }}-${{ runner.os }}-${{ matrix.os }}-gradle-
    - name: Cache gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle
        #key: ${{ matrix.java }}-${{ matrix.os }}-cache
        key: java-${{ matrix.java }}-${{ runner.os }}-${{ matrix.os }}-gradle-${{ hashFiles('**/.gradle/**') }}
        restore-keys: |
          java-${{ matrix.java }}-${{ runner.os }}-${{ matrix.os }}-gradle-
    ## This is also works:
    #- name: Cache
    #  uses: actions/cache@v1.1.2
    #  with:
    #    path: ~/.gradle
    #    key: ${{ matrix.java }}-${{ matrix.os }}-cache
